function neuroArtConfigInit(filename)
    % Write config file for neuroART.
    s = struct( ...
        'default', struct( ...
            'R', 5,...
            'DISPLAY', 200,...
            'EXID', 'RT_test1', ...
            'IMGFOLDER', pwd,...
            'IMG', 'Image_0001_0001', ...
            'FORMAT', 2, ...
            'RF', 2, ...
            'CFIND', 5, ...  % CHANGED: default to Cellpose
            'SCOPE', 1, ...
            'NUMCHAN', 1, ...
            'RCHAN', 2, ...
            'SLM', 1, ...
            'ROI', 1, ...
            'NET', 1, ...
            'CWIN', 1, ...
            'CWINF', 5 ...
        ), ...
        'options', struct( ...
            'FORMAT', [".raw", ".tif"], ...
            'CFIND', ["Manual","CaImAn","Cite-on","From File","Cellpose"], ...  % ADDED: Cellpose
            'SCOPE', ["Thorlabs B-Scope","Bruker Ultima 2P+","Bruker Ultima 2P","BEAMM(ScanImage)","MOM-Thors","Offline Mode"], ...
            'NUMCHAN', ["1","2","3","4"], ...
            'RF', ["Yes","No"], ...
            'RCHAN', ["Yes","No"], ...
            'SLM', ["None","BNS","PrairieLink"], ...
            'ROI', ["Not Filled","Filled"], ...
            'NET', ["MST","Correlations"], ...
            'CWIN', ["Cumulative","Fixed"] ...
        ), ...
        'python', struct( ...
            'complex_dynamics_path', "/path/to/complex_dynamics/src/", ...
            'env', "a_conda_environment", ...
            'use_python', true ...
        )...
    );
    fid = fopen(filename, 'w');
    fprintf(fid, '%s', jsonencode(s, PrettyPrint=true));
end
